parameters:
    default_locale: 'en'
    app.locales: ['en', 'fr']
    app.map_tile_url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
    app.map_attribution: '© OpenStreetMap contributors'
    app.photon_host_url: '%env(string:PHOTON_HOST_URL)%'
    app.uploads_dir: '%kernel.project_dir%/public/uploads'
    .container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

when@test:
    services:
        App\Tests\Factory\:
            resource: '../tests/Factory'
